#! /usr/bin/env bash

# This README file instructs how to build complexity.
#
# The following instructions build complexity. It can be run with the following
# command:
# 	bash README

name=complexity

for dir in content lib image
do
	if [ -f $dir/README ]
	then
		cd $dir
		bash README
		cd ..
	fi
done

pdflatex $name
bibtex $name
pdflatex $name
pdflatex $name

# publish to the web
output=../../../docs/lights_out
if [ -d $output ]
then
    echo "publishing"
    cp $name.pdf $output
else
    echo "$output"
fi
